import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { InventoryTransactionsService } from '../inventory-transactions.service';
 import { IInventoryTransactions
 } from '../iinventory-transactions';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';

import { ProductsService } from 'src/app/entities/products/products.service';

@Component({
  selector: 'app-inventory-transactions-new',
  templateUrl: './inventory-transactions-new.component.html',
  styleUrls: ['./inventory-transactions-new.component.scss']
})
export class InventoryTransactionsNewComponent extends BaseNewComponent<IInventoryTransactions> implements OnInit {
  
    title:string = "New InventoryTransactions";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<InventoryTransactionsNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public inventoryTransactionsService: InventoryTransactionsService,
		public errorService: ErrorService,
		public productsService: ProductsService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, inventoryTransactionsService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'InventoryTransactions';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: ['12:00 AM'],
      quantity: ['', Validators.required],
      transactionType: ['', Validators.required],
      productId: [''],
      productsDescriptiveField: [''],
    });
    
    this.fields = [
              {
      		  name: 'transactionType',
      		  label: 'transaction Type',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'quantity',
      		  label: 'quantity',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
              {
      		  name: 'createdAt',
      		  label: 'created At',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      		},
      		{
      		  name: 'createdAtTime',
      		  label: 'created At Time',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Time
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
			{
				column: [
					{
						key: 'productId',
						value: undefined,
						referencedkey: 'id'
					},
					  
				],
				isParent: false,
				table: 'products',
				type: 'ManyToOne',
				service: this.productsService,
				label: 'products',
				descriptiveField: 'productsDescriptiveField',
				referencedDescriptiveField: 'id',
		    
			},
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let inventoryTransactions = this.itemForm.getRawValue();


	    inventoryTransactions.createdAt = this.dataService.combineDateAndTime(inventoryTransactions.createdAt, inventoryTransactions.createdAtTime);
	    delete inventoryTransactions.createdAtTime;

        super.onSubmit(inventoryTransactions);

	}
    
}
