import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { OrdersService } from '../orders.service';
import { IOrders
 } from '../iorders';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { UsersService } from 'src/app/admin/user-management/users/users.service';

@Component({
  selector: 'app-orders-details',
  templateUrl: './orders-details.component.html',
  styleUrls: ['./orders-details.component.scss']
})
export class OrdersDetailsComponent extends BaseDetailsComponent<IOrders> implements OnInit {
	title = 'Orders';
	parentUrl = 'orders';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public ordersService: OrdersService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
		public usersService: UsersService,
		public globalPermissionService: GlobalPermissionService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, ordersService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Orders';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: [''],
      id: [{value: '', disabled: true}, Validators.required],
      status: [''],
      totalAmount: ['', Validators.required],
      userId: [''],
      usersDescriptiveField : [''],
      
    });
    
    this.fields = [
        {
		  name: 'totalAmount',
		  label: 'total Amount',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.Number,
	    },
        {
		  name: 'status',
		  label: 'status',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
      ];
      
  }
  
  onItemFetched(item: IOrders) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.ordersService.formatDateStringToAMPM(item.createdAt));
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'orderId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: true,
		table: 'orderItems',
		type: 'OneToMany',
		label: 'orderItems',
		},
      {
        column: [
	        {
	          key: 'userId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: false,
		table: 'users',
		type: 'ManyToOne',
		label: 'users',
		service: this.usersService,
		descriptiveField: 'usersDescriptiveField',
	    referencedDescriptiveField: 'id',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let orders = this.itemForm.getRawValue();


	    orders.createdAt = this.dataService.combineDateAndTime(orders.createdAt, orders.createdAtTime);
	    delete orders.createdAtTime;

        super.onSubmit(orders);
	}
}
