import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { CategoriesService } from '../categories.service';
 import { ICategories
 } from '../icategories';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-categories-new',
  templateUrl: './categories-new.component.html',
  styleUrls: ['./categories-new.component.scss']
})
export class CategoriesNewComponent extends BaseNewComponent<ICategories> implements OnInit {
  
    title:string = "New Categories";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<CategoriesNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public categoriesService: CategoriesService,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, categoriesService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'Categories';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: ['12:00 AM'],
      description: [''],
      name: ['', Validators.required],
      updatedAt: [''],
	  updatedAtTime: ['12:00 AM'],
    });
    
    this.fields = [
              {
      		  name: 'updatedAt',
      		  label: 'updated At',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      		},
      		{
      		  name: 'updatedAtTime',
      		  label: 'updated At Time',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Time
      	    },
              {
      		  name: 'name',
      		  label: 'name',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'description',
      		  label: 'description',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'createdAt',
      		  label: 'created At',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      		},
      		{
      		  name: 'createdAtTime',
      		  label: 'created At Time',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Time
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let categories = this.itemForm.getRawValue();


	    categories.createdAt = this.dataService.combineDateAndTime(categories.createdAt, categories.createdAtTime);
	    delete categories.createdAtTime;
	    categories.updatedAt = this.dataService.combineDateAndTime(categories.updatedAt, categories.updatedAtTime);
	    delete categories.updatedAtTime;

        super.onSubmit(categories);

	}
    
}
