import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { TimesheetsService } from '../timesheets.service';
 import { ITimesheets
 } from '../itimesheets';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { TasksService } from 'src/app/entities/tasks/tasks.service';
import { UsersService } from 'src/app/admin/user-management/users/users.service';

@Component({
  selector: 'app-timesheets-new',
  templateUrl: './timesheets-new.component.html',
  styleUrls: ['./timesheets-new.component.scss']
})
export class TimesheetsNewComponent extends BaseNewComponent<ITimesheets> implements OnInit {
  
    title:string = "New Timesheets";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<TimesheetsNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public timesheetsService: TimesheetsService,
		public errorService: ErrorService,
		public tasksService: TasksService,
		public usersService: UsersService,
		public globalPermissionService: GlobalPermissionService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, timesheetsService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'Timesheets';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: ['12:00 AM'],
      date: ['', Validators.required],
      hoursWorked: ['', Validators.required],
      taskId: [''],
      tasksDescriptiveField: [''],
      userId: [''],
      usersDescriptiveField: [''],
    });
    
    this.fields = [
              {
      		  name: 'hoursWorked',
      		  label: 'hours Worked',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
              {
      		  name: 'date',
      		  label: 'date',
      		  isRequired: true,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      	    },
              {
      		  name: 'createdAt',
      		  label: 'created At',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      		},
      		{
      		  name: 'createdAtTime',
      		  label: 'created At Time',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Time
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
			{
				column: [
					{
						key: 'taskId',
						value: undefined,
						referencedkey: 'id'
					},
					  
				],
				isParent: false,
				table: 'tasks',
				type: 'ManyToOne',
				service: this.tasksService,
				label: 'tasks',
				descriptiveField: 'tasksDescriptiveField',
				referencedDescriptiveField: 'id',
		    
			},
			{
				column: [
					{
						key: 'userId',
						value: undefined,
						referencedkey: 'id'
					},
					  
				],
				isParent: false,
				table: 'users',
				type: 'ManyToOne',
				service: this.usersService,
				label: 'users',
				descriptiveField: 'usersDescriptiveField',
				referencedDescriptiveField: 'id',
		    
			},
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let timesheets = this.itemForm.getRawValue();


	    timesheets.createdAt = this.dataService.combineDateAndTime(timesheets.createdAt, timesheets.createdAtTime);
	    delete timesheets.createdAtTime;

        super.onSubmit(timesheets);

	}
    
}
