import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { TasksService } from '../tasks.service';
import { ITasks
 } from '../itasks';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { ProjectsService } from 'src/app/entities/projects/projects.service';
import { UsersService } from 'src/app/admin/user-management/users/users.service';

@Component({
  selector: 'app-tasks-details',
  templateUrl: './tasks-details.component.html',
  styleUrls: ['./tasks-details.component.scss']
})
export class TasksDetailsComponent extends BaseDetailsComponent<ITasks> implements OnInit {
	title = 'Tasks';
	parentUrl = 'tasks';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public tasksService: TasksService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
		public projectsService: ProjectsService,
		public usersService: UsersService,
		public globalPermissionService: GlobalPermissionService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, tasksService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Tasks';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: [''],
      description: [''],
      dueDate: [''],
      id: [{value: '', disabled: true}, Validators.required],
      name: ['', Validators.required],
      status: [''],
      projectId: [''],
      projectsDescriptiveField : [''],
      assigneeId: [''],
      usersDescriptiveField : [''],
      
    });
    
    this.fields = [
        {
		  name: 'status',
		  label: 'status',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'name',
		  label: 'name',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'dueDate',
		  label: 'due Date',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
	    },
        {
		  name: 'description',
		  label: 'description',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
      ];
      
  }
  
  onItemFetched(item: ITasks) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.tasksService.formatDateStringToAMPM(item.createdAt));
    this.itemForm.get('dueDate')?.setValue(item.dueDate? new Date(item.dueDate): null);
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'projectId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: false,
		table: 'projects',
		type: 'ManyToOne',
		label: 'projects',
		service: this.projectsService,
		descriptiveField: 'projectsDescriptiveField',
	    referencedDescriptiveField: 'id',
		},
      {
        column: [
	        {
	          key: 'taskId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: true,
		table: 'timesheets',
		type: 'OneToMany',
		label: 'timesheets',
		},
      {
        column: [
	        {
	          key: 'assigneeId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: false,
		table: 'users',
		type: 'ManyToOne',
		label: 'users',
		service: this.usersService,
		descriptiveField: 'usersDescriptiveField',
	    referencedDescriptiveField: 'id',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let tasks = this.itemForm.getRawValue();


	    tasks.createdAt = this.dataService.combineDateAndTime(tasks.createdAt, tasks.createdAtTime);
	    delete tasks.createdAtTime;

        super.onSubmit(tasks);
	}
}
