import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { OrderItemsService } from '../order-items.service';
 import { IOrderItems
 } from '../iorder-items';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { OrdersService } from 'src/app/entities/orders/orders.service';
import { ProductsService } from 'src/app/entities/products/products.service';

@Component({
  selector: 'app-order-items-new',
  templateUrl: './order-items-new.component.html',
  styleUrls: ['./order-items-new.component.scss']
})
export class OrderItemsNewComponent extends BaseNewComponent<IOrderItems> implements OnInit {
  
    title:string = "New OrderItems";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<OrderItemsNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public orderItemsService: OrderItemsService,
		public errorService: ErrorService,
		public ordersService: OrdersService,
		public productsService: ProductsService,
		public globalPermissionService: GlobalPermissionService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, orderItemsService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'OrderItems';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      price: ['', Validators.required],
      quantity: ['', Validators.required],
      orderId: [''],
      ordersDescriptiveField: [''],
      productId: [''],
      productsDescriptiveField: [''],
    });
    
    this.fields = [
              {
      		  name: 'quantity',
      		  label: 'quantity',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
              {
      		  name: 'price',
      		  label: 'price',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
			{
				column: [
					{
						key: 'orderId',
						value: undefined,
						referencedkey: 'id'
					},
					  
				],
				isParent: false,
				table: 'orders',
				type: 'ManyToOne',
				service: this.ordersService,
				label: 'orders',
				descriptiveField: 'ordersDescriptiveField',
				referencedDescriptiveField: 'id',
		    
			},
			{
				column: [
					{
						key: 'productId',
						value: undefined,
						referencedkey: 'id'
					},
					  
				],
				isParent: false,
				table: 'products',
				type: 'ManyToOne',
				service: this.productsService,
				label: 'products',
				descriptiveField: 'productsDescriptiveField',
				referencedDescriptiveField: 'id',
		    
			},
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let orderItems = this.itemForm.getRawValue();



        super.onSubmit(orderItems);

	}
    
}
