import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { InventoryTransactionsService } from '../inventory-transactions.service';
import { IInventoryTransactions
 } from '../iinventory-transactions';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';

import { ProductsService } from 'src/app/entities/products/products.service';

@Component({
  selector: 'app-inventory-transactions-details',
  templateUrl: './inventory-transactions-details.component.html',
  styleUrls: ['./inventory-transactions-details.component.scss']
})
export class InventoryTransactionsDetailsComponent extends BaseDetailsComponent<IInventoryTransactions> implements OnInit {
	title = 'InventoryTransactions';
	parentUrl = 'inventorytransactions';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public inventoryTransactionsService: InventoryTransactionsService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
		public productsService: ProductsService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, inventoryTransactionsService, errorService);
  }

	ngOnInit() {
		this.entityName = 'InventoryTransactions';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: [''],
      id: [{value: '', disabled: true}, Validators.required],
      quantity: ['', Validators.required],
      transactionType: ['', Validators.required],
      productId: [''],
      productsDescriptiveField : [''],
      
    });
    
    this.fields = [
        {
		  name: 'transactionType',
		  label: 'transaction Type',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'quantity',
		  label: 'quantity',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.Number,
	    },
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
      ];
      
  }
  
  onItemFetched(item: IInventoryTransactions) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.inventoryTransactionsService.formatDateStringToAMPM(item.createdAt));
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'productId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: false,
		table: 'products',
		type: 'ManyToOne',
		label: 'products',
		service: this.productsService,
		descriptiveField: 'productsDescriptiveField',
	    referencedDescriptiveField: 'id',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let inventoryTransactions = this.itemForm.getRawValue();


	    inventoryTransactions.createdAt = this.dataService.combineDateAndTime(inventoryTransactions.createdAt, inventoryTransactions.createdAtTime);
	    delete inventoryTransactions.createdAtTime;

        super.onSubmit(inventoryTransactions);
	}
}
