import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { ProjectsService } from '../projects.service';
 import { IProjects
 } from '../iprojects';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';


@Component({
  selector: 'app-projects-new',
  templateUrl: './projects-new.component.html',
  styleUrls: ['./projects-new.component.scss']
})
export class ProjectsNewComponent extends BaseNewComponent<IProjects> implements OnInit {
  
    title:string = "New Projects";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<ProjectsNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public projectsService: ProjectsService,
		public errorService: ErrorService,
		public globalPermissionService: GlobalPermissionService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, projectsService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'Projects';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: ['12:00 AM'],
      description: [''],
      endDate: [''],
      name: ['', Validators.required],
      startDate: [''],
      status: [''],
    });
    
    this.fields = [
              {
      		  name: 'status',
      		  label: 'status',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'startDate',
      		  label: 'start Date',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      	    },
              {
      		  name: 'name',
      		  label: 'name',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'endDate',
      		  label: 'end Date',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      	    },
              {
      		  name: 'description',
      		  label: 'description',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'createdAt',
      		  label: 'created At',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Date,
      		},
      		{
      		  name: 'createdAtTime',
      		  label: 'created At Time',
      		  isRequired: false,
      		  isAutoGenerated: false,
      		  type: FieldType.Time
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let projects = this.itemForm.getRawValue();


	    projects.createdAt = this.dataService.combineDateAndTime(projects.createdAt, projects.createdAtTime);
	    delete projects.createdAtTime;

        super.onSubmit(projects);

	}
    
}
