import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { SuppliersService } from '../suppliers.service';
import { ISuppliers
 } from '../isuppliers';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-suppliers-details',
  templateUrl: './suppliers-details.component.html',
  styleUrls: ['./suppliers-details.component.scss']
})
export class SuppliersDetailsComponent extends BaseDetailsComponent<ISuppliers> implements OnInit {
	title = 'Suppliers';
	parentUrl = 'suppliers';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public suppliersService: SuppliersService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, suppliersService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Suppliers';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      contactInfo: [''],
      createdAt: [''],
	  createdAtTime: [''],
      id: [{value: '', disabled: true}, Validators.required],
      name: ['', Validators.required],
      
    });
    
    this.fields = [
        {
		  name: 'name',
		  label: 'name',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
        {
		  name: 'contactInfo',
		  label: 'contact Info',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
      ];
      
  }
  
  onItemFetched(item: ISuppliers) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.suppliersService.formatDateStringToAMPM(item.createdAt));
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let suppliers = this.itemForm.getRawValue();


	    suppliers.createdAt = this.dataService.combineDateAndTime(suppliers.createdAt, suppliers.createdAtTime);
	    delete suppliers.createdAtTime;

        super.onSubmit(suppliers);
	}
}
