import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { ProductsService } from '../products.service';
import { IProducts
 } from '../iproducts';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';

import { CategoriesService } from 'src/app/entities/categories/categories.service';

@Component({
  selector: 'app-products-details',
  templateUrl: './products-details.component.html',
  styleUrls: ['./products-details.component.scss']
})
export class ProductsDetailsComponent extends BaseDetailsComponent<IProducts> implements OnInit {
	title = 'Products';
	parentUrl = 'products';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public productsService: ProductsService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
		public categoriesService: CategoriesService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, productsService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Products';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: [''],
      description: [''],
      id: [{value: '', disabled: true}, Validators.required],
      name: ['', Validators.required],
      price: ['', Validators.required],
      stock: [''],
      updatedAt: [''],
	  updatedAtTime: [''],
      categoryId: [''],
      categoriesDescriptiveField : [''],
      
    });
    
    this.fields = [
        {
		  name: 'updatedAt',
		  label: 'updated At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'updatedAtTime',
		  label: 'updated At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
        {
		  name: 'stock',
		  label: 'stock',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.Number,
	    },
        {
		  name: 'price',
		  label: 'price',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.Number,
	    },
        {
		  name: 'name',
		  label: 'name',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'description',
		  label: 'description',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
      ];
      
  }
  
  onItemFetched(item: IProducts) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.productsService.formatDateStringToAMPM(item.createdAt));
    this.itemForm.get('updatedAt')?.setValue(item.updatedAt? new Date(item.updatedAt): null);
    this.itemForm.get('updatedAtTime')?.setValue(this.productsService.formatDateStringToAMPM(item.updatedAt));
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'categoryId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: false,
		table: 'categories',
		type: 'ManyToOne',
		label: 'categories',
		service: this.categoriesService,
		descriptiveField: 'categoriesDescriptiveField',
	    referencedDescriptiveField: 'id',
		},
      {
        column: [
	        {
	          key: 'productId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: true,
		table: 'inventoryTransactions',
		type: 'OneToMany',
		label: 'inventoryTransactions',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let products = this.itemForm.getRawValue();


	    products.createdAt = this.dataService.combineDateAndTime(products.createdAt, products.createdAtTime);
	    delete products.createdAtTime;
	    products.updatedAt = this.dataService.combineDateAndTime(products.updatedAt, products.updatedAtTime);
	    delete products.updatedAtTime;

        super.onSubmit(products);
	}
}
