import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { CategoriesService } from '../categories.service';
import { ICategories
 } from '../icategories';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-categories-details',
  templateUrl: './categories-details.component.html',
  styleUrls: ['./categories-details.component.scss']
})
export class CategoriesDetailsComponent extends BaseDetailsComponent<ICategories> implements OnInit {
	title = 'Categories';
	parentUrl = 'categories';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public categoriesService: CategoriesService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, categoriesService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Categories';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: [''],
      description: [''],
      id: [{value: '', disabled: true}, Validators.required],
      name: ['', Validators.required],
      updatedAt: [''],
	  updatedAtTime: [''],
      
    });
    
    this.fields = [
        {
		  name: 'updatedAt',
		  label: 'updated At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'updatedAtTime',
		  label: 'updated At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
        {
		  name: 'name',
		  label: 'name',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'description',
		  label: 'description',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
      ];
      
  }
  
  onItemFetched(item: ICategories) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.categoriesService.formatDateStringToAMPM(item.createdAt));
    this.itemForm.get('updatedAt')?.setValue(item.updatedAt? new Date(item.updatedAt): null);
    this.itemForm.get('updatedAtTime')?.setValue(this.categoriesService.formatDateStringToAMPM(item.updatedAt));
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'categoryId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: true,
		table: 'products',
		type: 'OneToMany',
		label: 'products',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let categories = this.itemForm.getRawValue();


	    categories.createdAt = this.dataService.combineDateAndTime(categories.createdAt, categories.createdAtTime);
	    delete categories.createdAtTime;
	    categories.updatedAt = this.dataService.combineDateAndTime(categories.updatedAt, categories.updatedAtTime);
	    delete categories.updatedAtTime;

        super.onSubmit(categories);
	}
}
